/*: Playground - noun: a place where people can play

 ## Contents
 
 1. Lesson 1 (Iterations)
     - [BinaryGap](BinaryGap)
 1. Lesson 2 (Arrays)
     - [OddOccurrencesInArray](OddOccurrencesInArray)
     - [CyclicRotation](CyclicRotation)
 1. Lesson 3 (Time Complexity)
     - [PermMissingElem](PermMissingElem)
     - [TapeEquilibrium](TapeEquilibrium)
     - [FrogJmp](FrogJmp)
 1. Lesson 4 (Countring Elements)
     - [PermCheck](PermCheck)
     - [FrogRiverOne](FrogRiverOne)
     - [MissingInteger](MissingInteger)
     - [MaxCounters](MaxCounters)
 1. Lesson 5 (Prefix Sums)
     - [CountDiv](CountDiv)
     - [PassingCars](PassingCars)
     - [MinAvgTwoSlice](MinAvgTwoSlice)
     - [GenomicRangeQuery](GenomicRangeQuery)
 1. Lesson 6 (Sorting)
     - [Distinct](Distinct)
     - [Triangle](Triangle)
     - [MaxProductOfThree](MaxProductOfThree)
     - [NumberOfDiscIntersections](NumberOfDiscIntersections)
 1. Lesson 7 (Stacks and Queues)
     - [StoneWall](StoneWall)
     - [Brackets](Brackets)
     - [Nesting](Nesting)
     - [Fish](Fish)
 1. Lesson 8 (Leader)
     - [EquiLeader](EquiLeader)
     - [Dominator](Dominator)
 1. Lesson 9 (Maximum slice problem)
     - [MaxProfit](MaxProfit)
     - [MaxSliceSum](MaxSliceSum)
     - [MaxDoubleSliceSum](MaxDoubleSliceSum)
 1. Lesson 10 (Prime and composite numbers)
     - [MinPerimeterRectangle](MinPerimeterRectangle)
     - [CountFactors](CountFactors)
     - [Flags](Flags)

*/

